server:
  port: 8085
spring:
  datasource:
    url: jdbc:mysql://localhost:3306/document_sharing?useUnicode=true&characterEncoding=utf8&useSSL=false&serverTimezone=Hongkong
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: root
    password: root123
    type: com.alibaba.druid.pool.DruidDataSource
mybatis:
  config-location: classpath:spring-config.xml
  mapper-locations: classpath:mapper/*.xml
